/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer; //create CustomerGUI JFrame inside the PresentationLayer

import BusinessLayer.Customer; //import Customer class from BusinessLayer package
import java.util.ArrayList; //import Arraylist funstions

/**
 *
 * @author Administrator
 */
public class CustomerGUI extends javax.swing.JFrame { //inhert swing JFrame for GUI functions 

    /**
     * Creates new form LoginMenu
     */
    public CustomerGUI() { //main function of the program
        initComponents(); //initComponents method is read only to keep full control for the IDE
        setExtendedState(MAXIMIZED_BOTH); //maximized the window in runtime
        jOptionPane1.setVisible(false); //invisible the jOptionPane
        fillCusId(); //call fillCusId sub program
        fillTable(); //call fillTablecus sub program

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNew = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCusID = new javax.swing.JTextField();
        txtTeleNo = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        cmbCusID = new javax.swing.JComboBox();
        txtCusName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCus = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Menu");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Commands"));

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtSearchMouseReleased(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addGap(18, 18, 18)
                .addComponent(btnNew)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Customer Information"));

        jLabel1.setText("Customer ID");

        jLabel2.setText("Customer Name");

        jLabel3.setText("Address");

        jLabel4.setText("Telephone No");

        cmbCusID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCusIDItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtTeleNo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbCusID, 0, 82, Short.MAX_VALUE))
                    .addComponent(txtCusName))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTeleNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Item List"));

        tblCus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer ID", "Customer Name", "Address", "Telephone No"
            }
        ));
        tblCus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCus);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\JSaji\\Desktop\\sss.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu2.setText("Edit");

        jMenuItem1.setText("Item");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Order");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        clearScreen(); //call the clearScreen sub problem
        for (int x = (int) cmbCusID.getItemCount() + 1; x > 0; x++) { //get a customer count of the cmbcusID and create a loop
            String y = "Cus0"; //create new string variable
            String z = y + x; //and equal the String variable and the Integer variable
            txtCusID.setText(z); //set the value to the txtCusID label
            break; //break the loop
        }
    }//GEN-LAST:event_btnNewActionPerformed

    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        if (txtSearch.getText().equalsIgnoreCase("Search")) {
            txtSearch.setText("");
        } else {
        }
    }//GEN-LAST:event_txtSearchMouseClicked

    private void txtSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseExited
        if (txtSearch.getText().equalsIgnoreCase("")) {
            txtSearch.setText("Search");
        } else {
        }
    }//GEN-LAST:event_txtSearchMouseExited

    private void txtSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseEntered
        //txtSearch.setText("Search");
    }//GEN-LAST:event_txtSearchMouseEntered

    private void txtSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseReleased
        //txtSearch.setText("Search");
    }//GEN-LAST:event_txtSearchMouseReleased

    private void txtSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMousePressed
        //txtSearch.setText("Search");
    }//GEN-LAST:event_txtSearchMousePressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

        String searchCusName = txtSearch.getText(); //get CustomerName from the txtSearch textfield and pass to the searchCusName variable
        ArrayList<Customer> cusList = new Customer().searchCus(searchCusName); //pass the CustomerName to the searchCustomer sub program and get entire items from the database depends on the CustomerName
        Object obj[][] = new Object[cusList.size()][5]; //create new object for the table
        int x = 0; //create new variable
        for (Customer cusObj : cusList) { //use for each loop to display entire details
            obj[x][0] = cusObj.getCusID(); //for first column to insert CusID
            obj[x][1] = cusObj.getCusName(); //for second column to insert CusName
            obj[x][2] = cusObj.getAddress(); //for third column to insert Address
            obj[x][3] = cusObj.getTeleNo(); //for forth column to insert TelePhoneNo
            x++; //increate loop iteration

        }

        tblCus.setModel(new javax.swing.table.DefaultTableModel( //create new table models using swing
                obj, //declare the object here
                new Object[]{ //create new object
                    "Customer ID", "Customer Name", "Address", "Telephone No" //give the column names
                }));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        if (txtSearch.getText().equalsIgnoreCase("Search")) {
            txtSearch.setText("");
        } else {
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Customer cusObj = new Customer(); //create object for Customer class
        cusObj.setCusID(txtCusID.getText()); //get CusID from txtMovieID textfield
        cusObj.setCusName(txtCusName.getText()); //get CusName from txtMovieID textfield
        cusObj.setAddress(txtAddress.getText()); //get Address from txtMovieID textfield
        cusObj.setTeleNo(s2I(txtTeleNo.getText())); //get Email from txtMovieID textfield

        boolean result = cusObj.addCus(cusObj); //add to the addCustomer sub program
        if (result) { //if the result equals true
            fillCusId(); //call the fillTablecus subprogram
            fillTable(); //call the fillCusId subprogram
            String Message = "Customer Successfully Added to the DataBase"; //display the message
            String Result = "Message";
            jOptionPane1.showMessageDialog(this, Message, Result, WIDTH, null);
        } else {
            String ERROR = "Error in Adding to the database"; //display the error message
            String Result = "ERROR";
            jOptionPane1.showMessageDialog(this, ERROR, Result, WIDTH, null);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        Customer cusObj = new Customer(); //create object for Customer class
        cusObj.setCusID(txtCusID.getText()); //get CusID from txtCusID textfield
        cusObj.setCusName(txtCusName.getText()); //get CusName from txtCusName textfield
        cusObj.setAddress(txtAddress.getText()); //get Address from txtAddress textfield
        cusObj.setTeleNo(s2I(txtTeleNo.getText())); //get TelephoneNo from txtTeleNo textfield

        boolean result = cusObj.editCus(cusObj); //add to the editCustomer sub program
        if (result) { //if the result equals true
            fillCusId(); //call the fillTablecus subprogram
            fillTable(); //call the fillCusId subprogram
            String Message = "Customer Successfully Edited to the DataBase"; //display the message
            String Result = "Message";
            jOptionPane1.showMessageDialog(this, Message, Result, WIDTH, null);
        } else {
            String ERROR = "Error in editing to the database"; //display the error message
            String Result = "ERROR";
            jOptionPane1.showMessageDialog(this, ERROR, Result, WIDTH, null);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Customer cusObj = new Customer(); //create object for Customer class
        String CusID = txtCusID.getText(); //get the CustomerID from the txtCusID and pass it to the CustomerID
        boolean result = cusObj.removeCus(CusID); //Pass it to the removeCustomer subprogram 
        if (result) { //if the result equals true
            fillCusId(); //call the fillCusId subprogram
            fillTable(); //call the fillTable subprogram
            String Message = "Customer Successfully removed from the DataBase";
            String Result = "Message";
            jOptionPane1.showMessageDialog(this, Message, Result, WIDTH, null);
        } else {
            String ERROR = "Error in removing to the database";
            String Result = "ERROR";
            jOptionPane1.showMessageDialog(this, ERROR, Result, WIDTH, null);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cmbCusIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCusIDItemStateChanged
        String searchCusID = (String) cmbCusID.getSelectedItem(); //pass the cmbCusID combobox SelectedItem to variable
        Customer cusObjSearchById = new Customer().getCus(searchCusID); //create object for the Customer class and pass to the getCustomer sub program
        if (cusObjSearchById.getCusName() == null) {
        } else {
            txtCusID.setText(cusObjSearchById.getCusID());
            txtCusName.setText(cusObjSearchById.getCusName());
            txtAddress.setText(cusObjSearchById.getAddress());
            txtTeleNo.setText(I2s(cusObjSearchById.getTeleNo()));
        }
    }//GEN-LAST:event_cmbCusIDItemStateChanged

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
    }//GEN-LAST:event_txtSearchActionPerformed

    private void tblCusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCusMouseClicked
        int row = tblCus.getSelectedRow();
        String column = tblCus.getModel().getValueAt(row, 0).toString();
        Customer cusObjSearchById = new Customer().getCus(column);
        if (cusObjSearchById.getCusName() == null) {
        } else {
            cmbCusID.setSelectedItem(cusObjSearchById.getCusID());
            txtCusID.setText(cusObjSearchById.getCusID());
            txtCusName.setText(cusObjSearchById.getCusName());
            txtAddress.setText(cusObjSearchById.getAddress());
            txtTeleNo.setText(I2s(cusObjSearchById.getTeleNo()));
        }
    }//GEN-LAST:event_tblCusMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ItemGUI itemObj = new ItemGUI();
        itemObj.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        OrderGUI ordObj = new OrderGUI();
        ordObj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CustomerGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JComboBox cmbCusID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCus;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCusID;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTeleNo;
    // End of variables declaration//GEN-END:variables

    public int s2I(String value) { //this sub sub program used to convert String to Integer
        return Integer.parseInt(value); //convert the String to Integer and return the value
    }

    public String I2s(int value) { //this sub sub program used to convert Integer to String
        Integer con = new Integer(value); //convert the Integer to String
        return con.toString(); //return the String value
    }

    public void clearScreen() { //this sub program used to clear the textfields value
        txtCusID.setText("");
        txtCusName.setText("");
        txtAddress.setText("");
        txtTeleNo.setText("");
    }

    public void fillCusId() { //this sub program used to get entire CustomerIDs from the database
        cmbCusID.removeAllItems(); //remove all current cmbCusID combobox
        ArrayList<Customer> cusList = new Customer().getAllCus(); //get entire CustomerIDs from the database and save it from the ArrayList
        for (Customer cusObj : cusList) { //use for each loop to display entire details
            cmbCusID.addItem(cusObj.getCusID()); //add CustomerIDs to the cmbCusID combobox
        }
    }

    public void fillTable() { //this sub program used to get entire Customer details from the database and display from the table

        ArrayList<Customer> cusList = new Customer().getAllCusDB(); //get entire items from the database save to the ArrayList
        Object obj[][] = new Object[cusList.size()][5]; //create new object for the table
        int x = 0; //create new variable
        for (Customer cusObj : cusList) { //use for each loop to display entire details
            obj[x][0] = cusObj.getCusID(); //for first column to insert CusID
            obj[x][1] = cusObj.getCusName(); //for second column to insert CusName
            obj[x][2] = cusObj.getAddress(); //for third column to insert Address
            obj[x][3] = cusObj.getTeleNo(); //for forth column to insert Email
            x++; //increate loop iteration
        }


        tblCus.setModel(new javax.swing.table.DefaultTableModel( //create new table models using swing
                obj, //declare the object here
                new Object[]{ //create new object
                    "Customer ID", "Customer Name", "Address", "Telephone No" //give the column names
                }));
    }

    public void SearchID() {
        String searchItemName = txtSearch.getText();
        ArrayList<Customer> cusList = new Customer().searchCusID(searchItemName);
        Object obj[][] = new Object[cusList.size()][5];
        int x = 0;
        for (Customer cusObj : cusList) {

            obj[x][0] = cusObj.getCusID();
            obj[x][1] = cusObj.getCusName();
            obj[x][2] = cusObj.getAddress();
            obj[x][3] = cusObj.getTeleNo();
            x++;
        }


        tblCus.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new Object[]{
                    "Customer ID", "Customer Name", "Address", "Telephone No"
                }));
    }
}
