/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PresentationLayer;

import BusinessLayer.Customer;
import BusinessLayer.Item;
import BusinessLayer.LineItem;
import BusinessLayer.Order;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;

/**
 *
 * @author Saji
 */
public class OrderGUI extends javax.swing.JFrame {
    
    ArrayList<OrderGUI> ItemList = new ArrayList<OrderGUI>();
    Order ordObj = new Order();
    private String mItemID;
    private String ItemID;
    private String mItem;
    private double mPrice;
    private int SIH;
    private int mQuantity;
    private double mTotal;
    //private int rowIndex;

    /**
     * Creates new form OrderGUI
     */
    public OrderGUI() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        fillTable();
        AddToList();
        BillID();
        fillCusId();
        BillIDGen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        btnItemGUI = new javax.swing.JButton();
        btnCustomerGUI = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddtoList = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblItemName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbBillID = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        lblBillID = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCusName = new javax.swing.JTextField();
        cmbCusID = new javax.swing.JComboBox();
        cmbPayment = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtPaid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        btnPrintBill = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnItemGUI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnItemGUI.setText("Item Menu");
        btnItemGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemGUIActionPerformed(evt);
            }
        });

        btnCustomerGUI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCustomerGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PresentationLayer/Untitled-3.jpg"))); // NOI18N
        btnCustomerGUI.setText("Customer");
        btnCustomerGUI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerGUIActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Monthly Report");

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PresentationLayer/Untitled-5.jpg"))); // NOI18N
        jButton4.setText("Logout");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PresentationLayer/Untitled-4.jpg"))); // NOI18N
        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnItemGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCustomerGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCustomerGUI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnItemGUI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItem);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtSearch.setText("Search");
        txtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtSearchMouseReleased(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Item Price");

        lblPrice.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPrice.setText("0.0");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Quantity");

        txtQuantity.setText("1");
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });
        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQuantityKeyTyped(evt);
            }
        });

        btnAddtoList.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddtoList.setText("Add to List");
        btnAddtoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddtoListActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Total");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotal.setText("0.0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Item Name");

        lblItemName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblItemName.setText("Select Item");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch)
                    .addComponent(btnAddtoList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel19))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(lblItemName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblPrice))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotal)
                    .addComponent(jLabel19))
                .addGap(21, 21, 21)
                .addComponent(btnAddtoList)
                .addGap(28, 28, 28))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Bill No.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Date :");

        Date.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Date.setForeground(new java.awt.Color(204, 51, 0));
        Date.setText("Date");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Cashier");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblBillID.setText("jLabel6");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBillID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Date)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(580, 580, 580)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(Date)
                    .addComponent(jLabel8)
                    .addComponent(cmbBillID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel)
                    .addComponent(lblBillID))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Customer");

        cmbCusID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCusIDItemStateChanged(evt);
            }
        });

        cmbPayment.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmbPayment.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cash", "Credit Card" }));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Payment By");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Paid");

        txtPaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaidActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Balance");

        txtBalance.setText("0.0");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Grand Total");

        lblGrandTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGrandTotal.setText("0.0");

        btnRemove.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnPrintBill.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrintBill.setText("Print Bill");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addGap(26, 26, 26)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtBalance, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPaid)
                                            .addComponent(txtCusName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbPayment, javax.swing.GroupLayout.Alignment.LEADING, 0, 154, Short.MAX_VALUE)
                                            .addComponent(lblGrandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnPrintBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCusID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cmbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblGrandTotal))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemove)
                    .addComponent(btnPrintBill))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblOrder);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void txtSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseClicked
        if (txtSearch.getText().equalsIgnoreCase("Search")) {
            txtSearch.setText("");
        } else {
        }
    }//GEN-LAST:event_txtSearchMouseClicked
    
    private void txtSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseEntered
        //txtSearch.setText("Search");
    }//GEN-LAST:event_txtSearchMouseEntered
    
    private void txtSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseExited
        if (txtSearch.getText().equalsIgnoreCase("")) {
            txtSearch.setText("Search");
        } else {
        }
    }//GEN-LAST:event_txtSearchMouseExited
    
    private void txtSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMousePressed
        //txtSearch.setText("Search");
    }//GEN-LAST:event_txtSearchMousePressed
    
    private void txtSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSearchMouseReleased
        //txtSearch.setText("Search");
    }//GEN-LAST:event_txtSearchMouseReleased
    
    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
   }//GEN-LAST:event_txtSearchActionPerformed
    
    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
   }//GEN-LAST:event_txtSearchKeyPressed
    
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        
        String searchItemName = txtSearch.getText();
        ArrayList<Item> itemList = new Item().searchItem(searchItemName);
        Object obj[][] = new Object[itemList.size()][4];
        int x = 0;
        for (Item itemObj : itemList) {
            obj[x][0] = itemObj.getItemID();
            obj[x][1] = itemObj.getItemName();
            obj[x][2] = itemObj.getPrice();
            obj[x][3] = itemObj.getStockInHand();
            x++;
        }
        
        
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new Object[]{
                    "Item ID", "Item Name", "Price", "Stock in hand"
                }));
    }//GEN-LAST:event_txtSearchKeyReleased
    
    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        if (txtSearch.getText().equalsIgnoreCase("Search")) {
            txtSearch.setText("");
        } else {
        }
    }//GEN-LAST:event_txtSearchKeyTyped
    
    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        int x = (s2I(txtQuantity.getText()));
        double y = (s2d(lblPrice.getText()));
        if ((lblPrice.getText()).equalsIgnoreCase("0.0")) {
            String Message = "Please select Item from the Dropdown list";
            jOptionPane1.showMessageDialog(this, Message);
            txtQuantity.setText("1");
            
        } else if (SIH == 0) {
            String Message = "Sorry " + mItem + " Stock not Available";
            jOptionPane1.showMessageDialog(this, Message);
            txtQuantity.setText("1");
            
        } else if (SIH < x) {
            String Message = "Enter Quantity Less than or Equal to " + I2s(SIH);
            jOptionPane1.showMessageDialog(this, Message);
            txtQuantity.setText("1");
            
        } else {
            mQuantity = x;
            double z = y * x;
            lblTotal.setText(d2s(z));
        }
    }//GEN-LAST:event_txtQuantityActionPerformed
    
    private void txtQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQuantityKeyTyped
   }//GEN-LAST:event_txtQuantityKeyTyped
    
    private void btnAddtoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddtoListActionPerformed
        if ((lblPrice.getText()).equalsIgnoreCase("0.0")) {
            String Message = "Please select Item from the Table";
            jOptionPane1.showMessageDialog(this, Message);
            
        } else if ((lblTotal.getText()).equalsIgnoreCase("0.0")) {
            String Message = "Please calculate the Total";
            jOptionPane1.showMessageDialog(this, Message);
            
        } else {
            OrderGUI ordObj = new OrderGUI();
            int row = tblItem.getSelectedRow();
            ordObj.mItemID = tblItem.getModel().getValueAt(row, 0).toString();
            ordObj.mItem = tblItem.getModel().getValueAt(row, 1).toString();
            ordObj.mPrice = s2d(lblPrice.getText());
            ordObj.mQuantity = s2I(txtQuantity.getText());
            ordObj.mTotal = s2d(lblTotal.getText());
            ItemList.add(ordObj);
            AddToList();
            Orderlist();
        }
    }//GEN-LAST:event_btnAddtoListActionPerformed
    
    private void cmbCusIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCusIDItemStateChanged
        String searchCusID = (String) cmbCusID.getSelectedItem();
        Customer cusObjSearchById = new Customer().getCus(searchCusID);
        if (cusObjSearchById.getCusName() == null) {
        } else {
            
            txtCusName.setText(cusObjSearchById.getCusName());
            
        }
    }//GEN-LAST:event_cmbCusIDItemStateChanged
    
    private void txtPaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaidActionPerformed
        
        if ((s2d(lblGrandTotal.getText())) <= (s2d(txtPaid.getText()))) { //if Grandtotal lessthan paid amount
            txtBalance.setText(d2s(s2d(txtPaid.getText()) - s2d(lblGrandTotal.getText()))); //set the balance amount to the txtBalance label
        } else {
            
            String Message = "Please enter the amount more than GrandTotal"; //display the error message 
            jOptionPane1.showMessageDialog(this, Message);
            txtPaid.setText(""); //set null to the txtPaid textfield

        }
    }//GEN-LAST:event_txtPaidActionPerformed
    
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        ClearItem();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private void btnItemGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemGUIActionPerformed
        ItemGUI ordGUI = new ItemGUI();
        ordGUI.setVisible(true);
    }//GEN-LAST:event_btnItemGUIActionPerformed
    
    private void btnCustomerGUIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerGUIActionPerformed
        CustomerGUI ordGUI = new CustomerGUI();
        ordGUI.setVisible(true);
    }//GEN-LAST:event_btnCustomerGUIActionPerformed
    
    private void tblItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemMouseClicked
        lblTotal.setText("0.0");
        int row = tblItem.getSelectedRow();
        String column = tblItem.getModel().getValueAt(row, 0).toString();
        Item itemObjSearchById = new Item().getItem(column);
        if (itemObjSearchById.getItemName() == null) {
        } else {
            
            mItemID = itemObjSearchById.getItemID();
            mItem = itemObjSearchById.getItemName();
            lblItemName.setText(itemObjSearchById.getItemName());
            lblPrice.setText(d2s(itemObjSearchById.getPrice()));
            SIH = itemObjSearchById.getStockInHand();
            
        }
    }//GEN-LAST:event_tblItemMouseClicked
    
    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int row = tblOrder.getSelectedRow();
        String Price = tblOrder.getModel().getValueAt(row, 4).toString();
        lblGrandTotal.setText(d2s(s2d(lblGrandTotal.getText()) - s2d(Price))); //set the balance amount to the txtBalance label
        ItemList.remove(row);
        AddToList();
        
        
    }//GEN-LAST:event_btnRemoveActionPerformed
    
    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
    }//GEN-LAST:event_tblOrderMouseClicked
    
    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
        LineItem itemObj = new LineItem();
        boolean result = false;
        for (OrderGUI ordObj : ItemList) {
            itemObj.setBillID(lblBillID.getText());
            itemObj.setItemID(ordObj.mItemID);
            itemObj.setItemName(ordObj.mItem);
            itemObj.setQuantity(ordObj.mQuantity);
            itemObj.setPrice(ordObj.mPrice);
            itemObj.setTotal(ordObj.mTotal);
            result = itemObj.addLineItem(itemObj);
        }
        if (result) {
            ordObj.setBillID(lblBillID.getText());
            ordObj.setCustomerID((String) cmbCusID.getSelectedItem());
            ordObj.setCustomerName(txtCusName.getText());
            ordObj.setGrandTotal(s2d(lblGrandTotal.getText()));
            result = ordObj.AddOrder(ordObj);
            
            PrintBill();
            
            
        }
    }//GEN-LAST:event_btnPrintBillActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new OrderGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JButton btnAddtoList;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCustomerGUI;
    private javax.swing.JButton btnItemGUI;
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox cmbBillID;
    private javax.swing.JComboBox cmbCusID;
    private javax.swing.JComboBox cmbPayment;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblBillID;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblItem;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JTextField txtCusName;
    private javax.swing.JTextField txtPaid;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public static String now(String dateFormat) {
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat(dateFormat);
        return sdf.format(cal.getTime());
    }
    
    public int s2I(String value) {
        return Integer.parseInt(value);
    }
    
    public String I2s(int value) {
        Integer con = new Integer(value);
        return con.toString();
    }
    
    public double s2d(String val) {
        return Double.parseDouble(val);
    }
    
    public String d2s(double val) {
        Double dou = new Double(val);
        return dou.toString();
    }
    
    public void fillTable() {
        
        ArrayList<Item> itemList = new Item().getAllItemDB();
        Object obj[][] = new Object[itemList.size()][4];
        int x = 0;
        for (Item itemObj : itemList) {
            obj[x][0] = itemObj.getItemID();
            obj[x][1] = itemObj.getItemName();
            obj[x][2] = itemObj.getPrice();
            obj[x][3] = itemObj.getStockInHand();
            x++;
        }
        
        tblItem.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new Object[]{
                    "Item ID", "Item Name", "Price", "Stock in hand"
                }));
    }
    
    public void AddToList() {    
        Object obj[][] = new Object[ItemList.size()][5];
        int x = 0;
        for (OrderGUI OrdObj : ItemList) {
            obj[x][0] = OrdObj.mItemID;
            obj[x][1] = OrdObj.mItem;
            obj[x][2] = OrdObj.mPrice;
            obj[x][3] = OrdObj.mQuantity;
            obj[x][4] = OrdObj.mTotal;
            
            x++;
        }
        
        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
                obj,
                new Object[]{
                    "ItemID", "Item", "Price", "Quantity", "Total"
                }));
    }
    
    public void Orderlist() {
        ordObj.setGrandTotal(ordObj.getGrandTotal() + s2d(lblTotal.getText())); //calcualte entire lineItem price
        lblGrandTotal.setText(d2s(ordObj.getGrandTotal())); //set lineItem total to the lblSubTotal label

    }
    
    public void BillID() {
        //clearScreen();
        for (int x = (int) cmbBillID.getItemCount() + 1; x > 0; x++) {
            String y = "BillID0";
            String z = y + x;
            lblBillID.setText(z);
            break;
        }
        
    }
    
    public void fillCusId() {
        cmbCusID.removeAllItems();
        ArrayList<Customer> CusList = new Customer().getAllCus();
        for (Customer cusObj : CusList) {
            cmbCusID.addItem(cusObj.getCusID());
        }
    }
    
    public void PrintBill() {
        
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in)); //create new bufferreader for input
        try (FileWriter fw = new FileWriter("IsuruLankaBakery.txt")) { //using try for new filewrite
            fw.write("");//blank line
            fw.write("Welcome to Isuru Lanka Bakery" + "\r\n");
            fw.write("\r\n");
            String GetListBill = lblBillID.getText();
            ArrayList<LineItem> itemList = new LineItem().getList(GetListBill); //using ArrayList to get all lineItem details

            int x = 0; //create new variable
            for (LineItem movObj : itemList) { //using foreach loop to write entire lineItem details to the file

                fw.write(movObj.getItemName() + "  Price = " + movObj.getPrice() + "  Quantity = " + movObj.getQuantity() + "  Total = " + movObj.getTotal() + "\r\n");
                
                x++; //increate loop iteration
            }
            fw.write("\r\n"); //go for the new line
            fw.write("Customer Name = " + txtCusName.getText() + "\r\n");
            fw.write("\r\n");
            fw.write("Grand Total = " + lblGrandTotal.getText() + "\r\n");
            fw.write("\r\n");
            fw.write("Payment Mode = " + (String) cmbPayment.getSelectedItem() + "\r\n");
            fw.write("\r\n");
            fw.write("Paid = " + txtPaid.getText() + "\r\n");
            fw.write("\r\n");
            fw.write("Balance = " + txtBalance.getText() + "\r\n");
            fw.write("\r\n");
            fw.write("Thank You come again...");
            String Message = "Bill Successfully Printed"; //display the error message 
            jOptionPane1.showMessageDialog(this, Message);
            BillIDGen();
            BillID();
            ClearItem();
        } catch (IOException exc) { //if any errors occur it will catch the errors
        }
        
    }
    
    public void BillIDGen() {
        
        cmbBillID.removeAllItems(); //remove all current cmbItemID combobox
        ArrayList<Order> ItemList = new Order().getAllItem(); //get entire ItemIDs from the database and save it from the ArrayList
        for (Order itemObj : ItemList) { //use for each loop to display entire details
            cmbBillID.addItem(itemObj.getBillID()); //add ItemIDs to the cmbItemID combobox

        }
    }
    
    public void ClearItem() {
        for (int row = 0; row <= ItemList.size(); row++) {
            ItemList.remove(row);
        }
        AddToList();
        lblItemName.setText("Select Item");
        lblPrice.setText("0.0");
        txtQuantity.setText("1");
        lblTotal.setText("0.0");
        txtCusName.setText("");
        lblGrandTotal.setText("0.0");
        txtPaid.setText("");
        txtBalance.setText("0.0");
        
        ClearItem();
    }
}
